reconcillation:
  dailyRated:
    fileName: "MicrosoftRecncilationFIles/FuntionalTestData/G004733043_DailyRatedusageLineItems.csv"
  oneTime:
    fileName: "MicrosoftRecncilationFIles/FuntionalTestData/G004733043_OneTimeInvoiceLineItems.csv"
mock:
  numberOfLineItems: 20000
  microsoftLineItemFetchCount: 2000

responseFolder:
  mainFolderPath: "/Users/prashantchauhan/Desktop/Target"
  dailyRatedPath:
    filesPath: "/__files/"
    mappingPath: "/mappings/"
  OneTimePath:
    filesPath: "/__files/"
    mappingPath: "/mappings/"


wireMock:
  response:
    teamName: "/iaas"
    useCaseName: "DTTest"
  delayDistribution:
    type: "lognormal"
    median: 500
    sigma: 0.4

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mockgenerator
    username: sa
    password: password

  sql:
    init:
      platform: org.hibernate.dialect.H2Dialect
