reconcillation:
  dailyRated:
    fileName: "MicrosoftRecncilationFIles/DailyRatedusageLineItems.csv"
  oneTime:
    fileName: "MicrosoftRecncilationFIles/OneTimeInvoiceLineItems.csv"
mock:
  numberOfLineItems: 100
  microsoftLineItemFetchCount: 10

responseFolder:
  mainFolderPath: "/Users/prashantchauhan/Desktop/Target"
  dailyRatedPath:
    filesPath: "/DailyRated/__files/"
    mappingPath: "/DailyRated/mappings/"
  OneTimePath:
    filesPath: "/OneTime/__files/"
    mappingPath: "/OneTime/mappings/"


wireMock:
  response:
    bodyFileNamePrefix: "lineitem"
  delayDistribution:
    type: "lognormal"
    median: 500
    sigma: 0.4

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mockgenerator
    username: sa
    password: password

  sql:
    init:
      platform: org.hibernate.dialect.H2Dialect
